name: MonWorkflowMaven

on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Maven tests
        run: mvn test

      - name: Maven package
        run: mvn package
      
      - name: Upload war
        uses: actions/upload-artifact@v2.2.2
        with:
          path: target/*.war
